import { product } from "./productClass";
import { reviewOfProduct } from "./reviewClass";
import { statusOfPdt } from "./allEnum";
import { categoriesOfPdt } from "./allEnum";
import { typeWarranty } from "./allEnum";
let allProducts:product[]=[];
let arrReview1:reviewOfProduct[]=[];
let review1=new reviewOfProduct("John",5);
let review2=new reviewOfProduct("Jack",4);
let review3=new reviewOfProduct("James",5);
arrReview1.push(review1);
arrReview1.push(review2);
arrReview1.push(review3);
let color:string[]=['red','gray','black'];
let product1=new product(1,"Oven","Its an electronic device",200000,statusOfPdt.available,categoriesOfPdt.electronic,"2 years",typeWarranty.limit,arrReview1,color);
product1.display();
product1.avgRating();
allProducts.push(product1);

let arrReview2: reviewOfProduct[]=[];
let reviewBook1=new reviewOfProduct("Amulya",5);
let reviewBook2=new reviewOfProduct("Ashwanth",4);
let reviewBook3=new reviewOfProduct("Niharaka",4);
arrReview2.push(reviewBook1);
arrReview2.push(reviewBook2);
arrReview2.push(reviewBook3);
let product2= new product(2,"IKIGAI","Its a The book about the lifestyle of a japanice guys",30000,statusOfPdt.notAvailable,categoriesOfPdt.books,"-",typeWarranty.unlimited,arrReview2);
product2.display();
product2.avgRating();
allProducts.push(product2);